export const TYPES = {
  AppReviewRepository: Symbol.for("AppReviewRepository"),
  AppReviewService: Symbol.for("AppReviewService"),
  BusinessRepository: Symbol.for("BusinessRepository"),
  BusinessService: Symbol.for("BusinessService"),
  FoodRepository: Symbol.for("FoodRepository"),
  FoodService: Symbol.for("FoodService"),
  ImageRepository: Symbol.for("ImageRepository"),
  ImageService: Symbol.for("ImageService"),
  ManagementRepository: Symbol.for("ManagementRepository"),
  ManagementService: Symbol.for("ManagementService"),
  ResourceRepository: Symbol.for("ResourceRepository"),
  ResourceService: Symbol.for("ResourceService"),
  ReviewRepository: Symbol.for("ReviewRepository"),
  ReviewService: Symbol.for("ReviewService"),
  UserRepository: Symbol.for("UserRepository"),
  UserService: Symbol.for("UserService"),
  CacheManager: Symbol.for("CacheManager"),
  MemoryCache: Symbol.for("MemoryCache"),
  UpstashCache: Symbol.for("UpstashCache"),
  StorageManager: Symbol.for("StorageManager"),
  StorageProvider: Symbol.for("StorageProvider"),
  AuthService: Symbol.for("AuthService"),
  DataSource: Symbol.for("DataSource"),
} as const;
