allowBuilds:
  '@embedded-postgres/linux-x64': true
  '@prisma/engines': true
  cpu-features: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  sharp: true
  ssh2: true
  unrs-resolver: true
  workerd: true
