services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - pnpm-store-data:/workspaces/project/.pnpm-store
      
    command: sleep infinity

volumes:
  pnpm-store-data: