services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - pnpm-store-data:/workspaces/project/.pnpm-store

      # important that these are synced with the host.
      - .:/workspaces/project/.devcontainer
      - ../.git:/workspaces/project/.git
    command: sleep infinity

volumes:
  pnpm-store-data: