name: Conditional Vercel Deploy

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  database-migration:
    if: contains(github.event.head_commit.message, '[deploy]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Prisma Migrations
        run: pnpm prisma migrate deploy
        env:
          DATABASE_DIRECT_URL: ${{ secrets.DATABASE_DIRECT_URL }}

  deploy-app:
    if: contains(github.event.head_commit.message, '[deploy]')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
